In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
Example_DataFrame = pd.DataFrame([['A',0,1,2,3],['B',4,5,6,7],['C',8,9,10,11],['D',12,13,14,15]])
print("step1",Example_DataFrame[0])
Example_DataFrame.index = Example_DataFrame[0] # Example_DataFrame.index is the variable that holds row names
print("step2",Example_DataFrame.iloc[:,1:])
Example_DataFrame = Example_DataFrame.iloc[:,1:] # we don't want the extra row, so we overwrite the dataframe variable without the extra column
print("step3",Example_DataFrame.index.name)
Example_DataFrame.index.name = None # This line is removing the column header for the index column (get rid of the 0 label)
print("step4",Example_DataFrame.columns)
Example_DataFrame.columns = ['Col_1', 'Col_2', 'Col_3','Col_4'] # Example_DataFrame.columns is the variabe that holds column names, 
                                                                 # we change them to something meaningful

step1 0    A
1    B
2    C
3    D
Name: 0, dtype: object
step2     1   2   3   4
0
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15
step3 0
step4 RangeIndex(start=1, stop=5, step=1)

In [3]:
Example_DataFrame

   Col_1  Col_2  Col_3  Col_4
A      0      1      2      3
B      4      5      6      7
C      8      9     10     11
D     12     13     14     15

## Basic rules for loc/iloc

**loc** - when you want to access specific locations by their row names. This is most useful when you are interested in particular rows of the dataframe. The syntax is driven by the row labels (integers by default, but we have given them string names in this example)

**iloc** - when you want to access a specific locations (or locations) by index. This is particularly useful when you have cumbersome column names or you want to access some portion of the dataframe. The syntax for iloc is driven by the location of each item (think of indices as coordinates for each value)

In [5]:
Example_DataFrame['Col_1'][0]

0

In [6]:
Example_DataFrame.iloc[0,0]

0

In [7]:
Example_DataFrame.loc['A']

Col_1    0
Col_2    1
Col_3    2
Col_4    3
Name: A, dtype: int64

In [32]:
mask = Example_DataFrame['Col_1']>5
mask

A    False
B    False
C     True
D     True
Name: Col_1, dtype: bool

In [34]:
Example_DataFrame[mask]

   Col_1  Col_2  Col_3  Col_4
C      8      9     10     11
D     12     13     14     15